#!/usr/bin/env bash

# only install the gitconfig is there
if ! [ -f git/gitconfig.local.symlink ]
then
  git_credential='cache'

  if [ "$(uname -s)" == "Darwin" ]
  then
    git_credential='osxkeychain'
  fi

  user 'What is your git author name?'
  read -e git_authorname
  user 'What is your git author email?'
  read -e git_authoremail

  sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

  success "Gitconfig successfully created"
else
  warn "Gitconfig already present"
fi
