#!/usr/bin/env bash
DOTFILES_INSTALL_DIR="$HOME/.dotfiles"
source "$DOTFILES_INSTALL_DIR/_utils/index"

# check if we can bootstrap the dotfiles
info "(☞ﾟヮﾟ)☞ Initiating dotfiles bootstrap"

warn "Dotfiles installer disabled, re-enable"
if [ ! -d $DOTFILES_ROOT ]; then
  fail "Dotfiles already bootstrapped!"
  fail_hard "Please use $HOME/scripts/install instead"
fi

# TODO clone repo and add it to -/dotfiles

# alright, let's do this
source "$DOTFILES_ROOT/scripts/install"
