#!/usr/bin/env bash

# exit immediately if a command exits with a non-zero status
set -e

source "$PWD/_utils/constants" # needs to be first
source "$PWD/_utils/messages"
source "$PWD/_utils/functions"
