#!/usr/bin/env bash

# exit immediately if a command exits with a non-zero status
set -e

source "${DOTFILES_ROOT}/_utils/constants.sh"
source "${DOTFILES_ROOT}/_utils/messages.sh"
source "${DOTFILES_ROOT}/_utils/functions.sh"
