#!/usr/bin/env bash
source "$DIR/utils/index"

info "Setup \033[0;37m[macOS]\033[0m"

source "$DIR/macos/defaults"
source "$DIR/macos/dock"

# create general code directory
if [ ! -d $CODE_DIR ]; then
  mkdir -p $CODE_DIR
  success "Code directory created"
else
  success "Code directory already created"
fi

# will return true or false
`fdesetup isactive`
if [ ! $? ]; then
  require_sudo
  sudo fdesetup enable
  success "FileVault successfully enabled"
else
  success "FileVault already enabled"
fi

# TODO need to decide on how to handle that
# mackup restore
# mackup backup

# run updates
source "$DIR/macos/update"
