#!/usr/bin/env bash
source "$DIR/utils/index"

info "Setup \033[0;37m[macOS]\033[0m"

source "$DIR/macos/defaults"
source "$DIR/macos/dock"

# create general code directory
if [ ! -d $CODE_DIR ]; then
  mkdir -p $CODE_DIR
  success "Code directory created"
else
  success "Code directory already created"
fi

# will return true or false
# TODO: needs to be fixed
# `fdesetup isactive`
# if [ ! $? ]; then
#   require_sudo
#   sudo fdesetup enable
#   success "FileVault successfully enabled"
# else
#   success "FileVault already enabled"
# fi

# restore app preferences
if [ ! -d "$HOME/.mackup" ]; then
  # copy custom apps as symlinks
  ln -Fs "$DIR/macos/.mackup" "$HOME/.mackup"
  # restore files
  mackup restore -f
  success "App preferences restored"
fi

# symlink hosts file
require_sudo
sudo ln -Fs "$DIR/macos/hosts" "/etc/hosts"

# run updates
source "$DIR/macos/update"
