# expand our horizon
tap "homebrew/bundle"
tap "homebrew/core"

# core binaries
brew "ack" # instead of grep
brew "awscli"
brew "bats" # "cat" on steroids
brew "coreutils" # those that come with macOS are outdated
brew "chrome-cli"
brew "dockutil"
brew "ffmpeg"
brew "findutils"
brew "gh"
brew "git"
brew "gnupg2"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "mackup"
brew "mas" # Mac App Store manager
brew "openssh"
brew "pinentry-mac"
brew "thefuck"
brew "trash" # manage the Trash bin
brew "tree" # list directories in a tree structure
brew "wget"

# terminal
brew "bash" # latest Bash version
brew "neovim" # instead of vim
brew "starship"
brew "tmux"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# development
brew "node"
brew "nginx"
brew "python"
brew "pyenv"
brew "pyenv-virtualenv"
brew "readline"
brew "openssl"
brew "zlib"
