#!/usr/bin/env bash
source "$PWD/_utils/index"

# check if homebrew is installed
if ! is_executable "brew"; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  success "Homebrew successfully installed"
else
  success "Homebrew already installed"
fi

# run updates
source "$PWD/homebrew/update"

# run install scripts
brew bundle --file=$DOTFILES_ROOT/homebrew/Brewfile --no-lock
brew bundle --file=$DOTFILES_ROOT/homebrew/Caskfile --no-lock

# manually download apps
source "$PWD/homebrew/manual"
