#!/usr/bin/env bash
source "$DIR/utils/index"

info "Update \033[0;37m[node]\033[0m"

npm update -g > /dev/null 2>&1
success "Updated npm"

npm install npm -g > /dev/null 2>&1
success "Updated global npm packages"
