#!/usr/bin/env bash
source "$DIR/utils/index"

info "Update \033[0;37m[node]\033[0m"

if is_executable "fnm"; then
  eval "$(fnm env)"
  fnm use default > /dev/null 2>&1

  npm install npm -g > /dev/null
  success "Updated npm"

  npm update -g > /dev/null
  success "Updated global npm packages"
fi
