#!/usr/bin/env bash
source "$DIR/utils/index"

info "Update \033[0;37m[node]\033[0m"

require_sudo

sudo npm update -g > /dev/null 2>&1
success "NPM updated"

sudo npm install npm -g > /dev/null 2>&1
success "Global NPM packages updated"
