#!/usr/bin/env bash
declare SSH_DIR="$HOME/.ssh"
declare APPLICATION_DIR="/Applications"
declare CODE_DIR="$HOME/Sites"

# settings
declare COMPUTER_NAME="Angelo's MacBook Air"
declare COMPUTER_NAME_SLUG="Angelos-MacBook-Air"
