#!/usr/bin/env bash
function empty () {
  printf "\n"
}

function info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

function user () {
  printf "\r  [ \033[0;35m>>\033[0m ] $1\n"
}

function success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

function warn () {
  printf "\r\033[2K  [\033[0;33mWARN\033[0m] $1\n"
}

function fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

function fail_hard () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ""
  exit
}
