#!/usr/bin/env bash
source "$DIR/utils/index"

info "Setup \033[0;37m[python]\033[0m"

if is_executable "uv"; then
  # install global python tooling in isolated environments
  uv tool install black > /dev/null 2>&1 || true
  success "Black successfully installed"
  uv tool install twine > /dev/null 2>&1 || true
  success "Twine successfully installed"
else
  fail_hard "uv is not installed, run the homebrew setup first!"
fi
