#!/usr/bin/env bash
source "$DIR/utils/index"

info "Setup \033[0;37m[python]\033[0m"

if test $(which python3); then
  export PIP_REQUIRE_VIRTUALENV=false
  pip3 install --upgrade setuptools > /dev/null 2>&1
  success "Setuptools successfully upgraded"
  pip3 install --upgrade pip > /dev/null 2>&1
  success "Pip successfully upgraded "
  pip3 install twine > /dev/null 2>&1
  success "Twine successfully installed"
  export PIP_REQUIRE_VIRTUALENV=true

  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  source ~/.poetry/env
  success "Successfully installed poetry"
fi
