#!/usr/bin/env bash
source "$PWD/utils/index"

# get latest repo state
info "Update \033[0;37m[repository]\033[0m"
git pull origin master -q
success "Updated repository"

# run general updates
source "$PWD/fonts/update"
source "$PWD/git/update"
source "$PWD/homebrew/update"
source "$PWD/node/update"
source "$PWD/python/update"

# system specific installs
if is_mac; then source "$PWD/macos/update"; fi
if is_linux; then source "$PWD/linux/update"; fi

info "👉 Updates finished"
