#!/usr/bin/env bash
source "$PWD/utils/index"

# get latest repo state
info "Running update scripts"
git pull origin master -q
success "Updated repository"

# run general updates
source "$PWD/fonts/update"
source "$PWD/git/update"
source "$PWD/homebrew/update"





source "$PWD/node/update"

# system specific installs
if is_mac; then source "$PWD/macos/update"; fi
if is_linux; then source "$PWD/linux/update"; fi
