#!/usr/bin/env bash
source "$PWD/utils/index"

# install zsh
info "Setup [apps]"

if [ -f "$HOME/.hyper.js" ] && [ is_mac ]; then
  # trigger hot reload
  cp -rf "$DOTFILES_ROOT/apps/config/.hyper.js" "$HOME/.hyper.js" > /dev/null 2>&1
  # create symlink for further upgrades
  ln -Fs "$DOTFILES_ROOT/apps/config/.hyper.js" "$HOME/.hyper.js"

  success "Successfully setup Hyper configs"
fi
