#!/usr/bin/env bash
source "$PWD/utils/index"

info "Setup \033[0;37m[zsh]\033[0m"

if [ ! -d "$HOME/.oh-my-zsh" ];then
  # run installation script
  export RUNZSH=no
  export CHSH=no
  export KEEP_ZSHRC=yes
  /bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  success "Oh-my-zsh successfully installed"
else
  success "Oh-my-zsh already setup"
fi
