#!/usr/bin/env bash
source "$DIR/utils/index"

info "Update \033[0;37m[zsh]\033[0m"

env ZSH="$ZSH" sh "$ZSH/tools/upgrade.sh" > /dev/null 2>&1
command rm -rf "$ZSH/log/update.lock"
# fix permissions if broken
compaudit | xargs chmod g-w,o-w > /dev/null 2>&1

success "Updated oh-my-zsh"
